# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a4296916d6b83a1fde9d6ebf61c1db771d36fec3e3cedc6f817b67fc2f3d37bb39a0c0bb1c847005fa41101bd296a2a4b909e5f23c29aff716cc815ea923f71

test:
  secret_key_base: e3bc2937e173940c00512bd4195e8057d81f7d0aceb9dcecf1b6fe19ee37e06590865399eb42ff53244e776684331944fdfecb2f8b8e526d9aa20adf5ea0bd4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
